export const appRoutes = {
  splash: "/",
  onboarding: "/onboarding",
  login: "/auth/login",
  register: "/auth/cadastro",
  forgotPassword: "/auth/recuperar-senha",
  home: "/app",
  booking: "/app/agendamento",
  appointmentDetails: "/app/agendamento/detalhes",
  checkout: "/app/checkout",
  pixPending: "/app/pix-pendente",
  confirmation: "/app/confirmacao",
  history: "/app/historico",
  profile: "/app/perfil",
  plans: "/app/planos",
  subscription: "/app/assinatura",
  cashback: "/app/cashback",
  coupons: "/app/cupons",
  notifications: "/app/notificacoes",
  admin: "/admin",
  adminSchedule: "/admin/agenda",
  adminClients: "/admin/clientes",
  adminBarbers: "/admin/barbeiros",
  adminServices: "/admin/servicos",
  adminFinance: "/admin/financeiro",
  adminReports: "/admin/relatorios",
  adminSettings: "/admin/configuracoes",
} as const;
